!com.gumjoe.twokeys.types.LocalConfig
keyboards: 
   keyboard: !com.gumjoe.twokeys.types.config.Keyboard
      dir: ./
      path: WAITING
      root: index.ahk
   keyboard_2: !com.gumjoe.twokeys.types.config.Keyboard
      dir: ./
      path: WAITING
      root: index.ahk
packs: {}
