type: multi

keyboards:
  Keyboard_1:
    !com.gumjoe.twokeys.generators.config.Keyboard
    path: /dev/input/by-id/xyz
    dir: ./Keyboard_1
    root: index.ahk
    hotkeys:
      A: MsgBox # Uses same shortcodes, specifies a function to run when hotkey is triggered
  Keyboard_2:
    !com.gumjoe.twokeys.generators.config.Keyboard
    path: /dev/input/by-id/xyz
    dir: "./Keyboard_2"
    map:
      A: DoAFunc # Key: ahk_file.ahk
      /UP/: MoveLayerUP

packs: # Packs of macros
  repos:
    github: github.com
    twokeys: repo.twokeys.com
    npm: npm.com
  install:
    npm:
      - 2Keys-program-JS
      - 2Keys-video-edit-premiere
      - 2Keys-standard-firefox
