permissions:
  ssh: true # Allows us to ssh into the raspberry pi to execute command to map keys to allow easy setup
  variables: true # Allows AHK scripts to interface with each other

keyboards:
  Keyboard_1:
    !com.gumjoe.twokeys.generators.config.Keyboard
    path: /dev/input/by-id/xyz
    dir: ./Keyboard_1
    root: index.ahk
    hotkeys:
      A: MsgBox # Uses same shortcodes, specifies a function to run when hotkey is triggered
  Keyboard_2:
    !com.gumjoe.twokeys.generators.config.Keyboard
    path: /dev/input/by-id/xyz
    dir: ./Keyboard_2
    map:
      G1: 909 # Assume macro remaps to 909
    hotkeys:
      A: DoAFunc # Function name
      $UP$: MoveLayerUP
      +$UP$: MoveCursorNextLayer
      +>$ENTER$: SomeFunction
      $ENTER$: GitCommitVSCODE
      (G1):
        type: up
        func: RunACMD
      $PRTSC$:
        type: down
        from: npm/vscode/editor # Load npm pack 2Keys-vscode and load the editor directory hotkeys in it
        func: CopyAll
      $LEFT$:
        type: down
        func: npm/premiere/preview-window:FiveFramesForward
    Keyboard_2:
      !com.gumjoe.twokeys.generators.config.Keyboard
      path: /dev/input/by-id/xyz
      dir: ./Keyboard_2
      include:
        - npm.stand-firefox.all
      

packs: # Packs of macros
  repos:
    github: github.com
    twokeys: repo.twokeys.com
    npm: npm.com
  install:
    npm:
      - 2Keys-vscode
      - 2Keys-video-edit-premiere
      - 2Keys-standard-firefox
