# Root 2Keys config
# Contains data about project
name: Name of project
id: 666666 # UUID
version: 1.0.0 # 2Keys version
sync: false

server:
  port: 8080
  perms:
    start-startup: false

detectors:
  - ./detector-pi.yml
  - ./detector-custom.yml
  - ./detector-interception.yml
  - ./detector-hasu.yml