!com.gumjoe.twokeys.types.LocalConfig
keyboards: 
   keyboard: !com.gumjoe.twokeys.types.config.Keyboard
      dir: ./
      path: WAITING
      root: index.ahk
      hotkeys:
         ^!7: MsgBox
    
      
packs: {}
