/*
 * This Java source file was generated by the Gradle 'init' task.
 * @overview Entry point for 2keys
 */
package com.gumjoe.twokeys;

import com.gumjoe.twokeys.cli.*;

public class App {
    public static void main(String[] args) {
        // Parse args
        CLI cli = new CLI();
        cli.startParse(args);
    }
}
