language: node_js
node_js:
  - lts/*
  - node

os: windows

# Default is fine here
before_install:
  # Convery lock file
  - cd packages/twokeys-server
  - choco install yarn
install:
  - "\"/c/Program Files (x86)/Yarn/bin/yarn\""
before_script:
  - npx ts-node ./scripts/bootstrap.ts
script:
  - npm run coverage
  - npx codecov
