language: node_js
node_js:
  - lts/*
  - node

os: windows

# Default is fine here
install:
  - cd server
  - npm i -g windows-build-tools
  - npm ci
script:
  - cd server
  - npm run coverage
  - npm add codecov
  - codecov