language: node_js
node_js:
  - lts/*
  - node

os: windows

# Fix build timeout. See https://travis-ci.community/t/build-timeout-but-actually-succeeded/2763
env:
  - YARN_GPG=no

cache:
  npm: true
  yarn: true
# Default is fine here
before_install:
  # Convert lock file & install protoc
  - choco install yarn protoc
install:
  - "\"/c/Program Files (x86)/Yarn/bin/yarn\" --frozen-lockfile"
before_script:
  - yarn wsrun -mtc precompile # precompile e.g. protobufs
  - yarn build -v
  - yarn workspace @twokeys/server run ts-node ./scripts/bootstrap.ts --debug
# NB: server tests ran separately as they assume the CWD is the server package
script:
  - yarn workspaces run coverage:log
  # - yarn workspaces run coverage
  # - bash <(curl -s https://codecov.io/bash)
