language: node_js
node_js:
  - lts/*
  - node

os: windows

# Default is fine here
before_install:
  # Convery lock file
  - cd server
  - choco install yarn
install:
  - C:\\Program Files (x86)\\Yarn\\bin\\yarn
script:
  - npm run coverage
  - npx codecov