language: node_js
node_js:
  - lts/*
  - node

os: windows

# Fix build timeout. See https://travis-ci.community/t/build-timeout-but-actually-succeeded/2763
env:
  - YARN_GPG=no

# Default is fine here
before_install:
  # Convery lock file
  - choco install yarn
install:
  - "\"/c/Program Files (x86)/Yarn/bin/yarn\""
before_script:
  - yarn workspace @twokeys/core run compile
  - yarn workspaces run compile
  - yarn workspace @twokeys/server run ts-node ./scripts/bootstrap.ts
script:
  - yarn workspaces run coverage
  - yarn run codecov
