language: node_js
node_js:
  - lts/*
  - node

os: windows

# Default is fine here
before_install:
  # Convery lock file
  - cd server
  - npm install -g synp
  - synp -s yarn.lock
install:
  - npm ci
script:
  - npm run coverage
  - npx codecov