language: node_js
node_js:
  - lts/*
  - node

os: windows

# Default is fine here
install:
  - cd server
  - yarn global add codecov
  - yarn install
script:
  - cd server
  - yarn run coverage
  - codecov