language: node_js
node_js:
  - lts/*
  - node

os: windows

# Default is fine here
install:
  - cd server
  - yarn global add windows-build-tools
  - yarn
script:
  - cd server
  - yarn run coverage
  - yarn add codecov
  - codecov