language: node_js
node_js:
  - lts/*
  - node

os: windows

# Default is fine here
before_install:
  # Convery lock file
  - cd server
  - choco install yarn
install:
  - yarn
script:
  - yarn run coverage
  - npx codecov