' FILE AUTO-GENERATED BY 2KEYS
' DO NOT MODIFY
' Project name: pi3
Set oShell = CreateObject("Wscript.Shell") 
Dim strArgs
strArgs = "cmd /c node D:\Users\Kishan\Documents\Projects\2Keys\example\pi3\.2Keys\daemon.js"
oShell.Run strArgs, 0, false
