/**
Copyright 2018 Kishan Sambhi

This file is part of 2Keys.

2Keys is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

2Keys is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with 2Keys.  If not, see <https://www.gnu.org/licenses/>.
*/
import { join } from "path";
import { homedir } from "os";
import { AppPath, AppPaths, Keyboard, UserspaceConfig } from "./interfaces";

/**
 * @overview Constants for 2Keys
 */
export const DEBUG: string = "debug";
export const DEFAULT_PORT: number = 9090;
export const CONFIG_FILE: string = "config.yml";
//export const AHK_LIB_PATH: string = "D:\\Users\\Kishan\\Documents\\Projects\\2Keys\\cli\\lib\\ahkdll-v1-release-master\\x64w\\AutoHotkey.dll";
export const AHK_LIB_PATH: string = "D:\\Users\\Kishan\\Documents\\Projects\\2Keys\\cli\\lib\\ahkdll-v2-release-master\\x64w\\AutoHotkey.dll";
export const AHK_DOWNLOAD_PATH = "https://codeload.github.com/HotKeyIt/ahkdll-v2-release/zip/master";
export const AHK_VERSION = "2.0.0-alpha"

// Default paths
export const DEFAULT_USERSPACE_ROOT: string = join(homedir(), ".2Keys");
export const DEFAULT_USERSPACE_CONFIG: string = join(homedir(), ".2Keys.rc.yml");
export const DEFAULT_USERSPACE_SOFTWARE_ROOT: string = join(DEFAULT_USERSPACE_ROOT, "software");
export const DEFAULT_USERSPACE_SOFTWARE_DOWNLOAD: string = join(DEFAULT_USERSPACE_SOFTWARE_ROOT, ".tmp"); // Where to download files to
export const DEFAULT_USERSPACE_SOFTWARE_PATHS: AppPaths = {
  ahk: {
    root: join(DEFAULT_USERSPACE_SOFTWARE_ROOT, "ahk"),
    dll: "./x64w/AutoHotkey.dll",
    exe: "./x64w/AutoHotkey.exe"  
  }
}
export const default_userspace_config: UserspaceConfig = {
  oobe: false,
  paths: {
    root: DEFAULT_USERSPACE_ROOT,
    software: DEFAULT_USERSPACE_SOFTWARE_ROOT,
  },
  software: {
    ahk: {
      version: "2.0.0-alpha",
      paths: {
        root: "./ahk",
        dll: "./x64w/AutoHotkey.dll",
        exe: "./x64w/AutoHotkey.exe",
      },
    },
  },
}
export const DEFAULT_HOTKEY_FILE_ROOT: string = "index.ahk";

// Default root AHK file
export const DEFAULT_AHK_ROOT_CONTENTS: string = `; File generated by 2Keys
; 2Keys AutoHotkey entry point

; Default AHK stuff
;#SingleInstance, force ; Uncomment this line if using AutoHotkey < v2
SetWorkingDir A_ScriptDir  ; Ensures a consistent starting directory.
;#Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.

; CONVERSION NOTICE 1
; All your hotkeys need to changed to functions
; Then, include the function to run in your config under the key mapping.
; The script with the function in should then be included below.
; See https://github.com/Gum-Joe/2Keys for help

; CONVERSION NOTICE 2
; Since the keyboards are plugged into a separte computer (the detector)
; You can't get keyboard states (and info. about the keyboards) using AutoHotkeys
; Soon we'll be adding a set of core libraries which will allow you to do, i.e.:
; #Include <2Keys/keyboards>
; keyboards.getState(keyboard, key)
; Syntax is subject to change

; CONVERSION NOTICE 3
; Depending on the version of AutoHotkey 2Keys is using
; You may need to migrate your scripts to AutoHotkey v2

; Include all your AutoHotkey scripts here
; i.e. #Include "run-apps.ahk"

`

// Default Service prefix
export const WINDOWS_DAEMON_PREFIX: string = "2Keys-";
export const WINDOWS_DAEMON_FILE: string = "daemon.js";
export const WINDOWS_DAEMON_FILE_VBS: string = "daemon.vbs";
export const WINDOWS_DAEMON_FILE_JS_TEMPLATE = join(__dirname, `../../assets/${WINDOWS_DAEMON_FILE}`)
export const WINDOWS_DAEMON_FILE_VBS_TEMPLATE = join(__dirname, `../../assets/${WINDOWS_DAEMON_FILE_VBS}`)
export const WINDOWS_DAEMON_PID_FILE = "daemon.pid"

// Local project stuff
export const DEFAULT_LOCAL_2KEYS: string = ".2Keys";  // Where local 2Keys files are, i.e. windows service files