/** Error codes */
export const APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND";
export const APPLICATION_ACCESS_ERROR = "APPLICATION_ACCESS_ERROR";
export const BAD_VAGRANT_EXIT_CODE = "VAGRANT_NONZERO_EXIT";