keyboards:
  keyboard_1:
    path: WAITING FROM DETECTOR
    dir: ./Keyboard_1
    root: index.ahk
  keyboard_2:
    path: WAITING FROM DETECTOR
    dir: ./Keyboard_2
    root: index.ahk
addresses:
  detector: 192.168.0.100
  server:
    ipv4: 192.168.0.12
    port: 9090
perms:
  ssh: true
