name: pi3
keyboards:
  keyboard_1:
    path: /dev/input/by-id/usb-Logitech_Gaming_Keyboard_G810_166A37573236-event-kbd
    dir: ./Keyboard_1
    root: index.ahk
    hotkeys:
      N: SendN
  keyboard_2:
    path: /dev/input/by-id/usb-Logitech_G513_Carbon_Tactile_105E376A3437-event-kbd
    dir: ./Keyboard_2
    root: index.ahk
    hotkeys:
      N: SendN
addresses:
  detector: 192.168.0.100
  server:
    ipv4: 192.168.0.14
    port: 9090
perms:
  ssh: true
