/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gumjoe.twokeys;

import com.gumjoe.twokeys.App;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
    }
}
