/**
 * File auto-generated by 2Keys
 * Used for windows service to start 2Keys server
 * Project name:
 * Root dir:
 * DO NOT MODIFY
 */
const { spawn } = require("child_process");
const { createWriteStream } = require("fs");
const { join } = require("path");

const root = "D:\\Users\\Kishan\\Documents\\Projects\\2Keys\\example\\4"

// CHDIR to root
process.chdir(root);

// Create log file
console.log("Creating log file...");
const date = new Date();
const logger = createWriteStream(join(root, ".2Keys", `${date.getFullYear()}.${date.getMonth()}.${date.getDate()} ${date.getHours()}.${date.getMinutes()}.${date.getSeconds()}.log`))

console.log("Starting 2Keys server for <NAME>...");
const server = spawn("2Keys", ["serve"], {
  shell: true
});

server.stdout.on("data", (data) => {
  logger.write(data);
});

server.stderr.on("data", (data) => {
  logger.write(data);
});

server.on("close", (code) => {
  console.log(`child process exited with code ${code}`);
  process.exit(code);
});

server.on("error", (err) => {
  console.error("Failed to start subprocess.");
  process.exit(1);
});