using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using YamlDotNet.RepresentationModel;
using YamlDotNet.Serialization;

namespace Keyboard
{
    public partial class DetectorWriter : Form
    {
        public DetectorWriter(string configFile, string HID)
        {
            Console.Write("Writing config....");
            InitializeComponent();
            hid.Text = "HID: " + HID;

            // Write
            // Load
            StringReader config = new StringReader(System.IO.File.ReadAllText(configFile));
            YamlStream yaml = new YamlStream();
            yaml.Load(config);

            // Get HID and edit value
            var mapping = (YamlMappingNode)yaml.Documents[0].RootNode;
            var keyboard = (YamlMappingNode)mapping.Children[new YamlScalarNode("keyboard")];
            keyboard.Children[new YamlScalarNode("HID")] = HID;

            // Create string to write
            var serializer = new SerializerBuilder().Build();
            string configWrite = "# Config for keyboards for 2Keys\n# Generated by 2Keys\n# DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING\n!com.gumjoe.twokeys.types.LocalConfig\n" + serializer.Serialize(mapping);

            // Write
            System.IO.File.WriteAllText(configFile, configWrite);
            Application.Exit();
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }
    }
}
