# Stored in /home/twokeys/.2Keys/client.yml
# or /vagrant/config/client.yml (so easily linked back to server)
# Config for the detector, created from the server side config
# This is because certain properties are needed by the detector but not by the controller

# 2Keys detector-linux provision script
twokeys:
  version: 1.0.0
  type: CLIENT_SETUP

client:
  name: Some name
  id: some id
  roots: # Important directories
    config: /vagrant/config
    project: /vagrant/project
  server:
    ipv4: 10.0.2.2
    port: 8080