/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ClientSideKeyboardMap {
  /**
   * Contains information about what this config is for
   */
  twokeys: {
    /**
     * Version of 2Keys
     */
    version: string;
    /**
     * Tells us this is a KEYBOARD_MAP config.  KEYBOARD_MAP must be given for this value so we know we are parsing the right config
     */
    type: "KEYBOARD_MAP";
    /**
     * Tells us who created this config: CONTROLLER means server side, DETECTOR means the detector that runs on the client created this config
     */
    createdBy: "CONTROLLER" | "DETECTOR";
  };
  /**
   * Contains a map of keyboard UUIDs to /dev/input devices, with multiple allowed for each keyboard
   */
  keyboards: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: {
      /**
       * Path to file that represents the keyboard, usually in /dev/input
       */
      deviceFilePaths: string[];
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
