/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ClientSideConfig {
  /**
   * Contains information about the 2Keys install that provisioned this client
   */
  twokeys: {
    /**
     * Version of 2Keys
     */
    version: string;
    /**
     * Tells us this is a CLIENT_SETUP config.  CLIENT_SETUP must be given for this value so we know we are parsing the right config
     */
    type: string;
    [k: string]: unknown;
  };
  /**
   * Actual client config
   */
  client: {
    /**
     * Client name (from client side config)
     */
    name: string;
    /**
     * Client UUID (from client side config)
     */
    id: string;
    /**
     * Important directories on the client that the client needs to know about
     */
    roots: {
      /**
       * Directory to store config files such as this config and the keyboard map
       */
      config: string;
      /**
       * Directory where projects will be stored (sub-folder for each project), with a project index in the root
       */
      projects: string;
      [k: string]: unknown;
    };
    /**
     * Information about the 2Keys server this client is for
     */
    server: {
      /**
       * ipv4 address of server
       */
      ipv4: string;
      /**
       * Server port
       */
      port: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
