# Provisions a new client on the VM, i.e. sets it up for 2Keys to use for projects
---
- hosts: all
  tasks:
    # Provisions 2Keys detector software
    # TODO: Publish detector module/install locally to ensure this works, and then prevent ansible ignoring errors here
    - name: Provision 2Keys client
      become: true
      ignore_errors: yes # Remove this when provision works
      command: 2Keys provision -f /vagrant/config/provision.yml #