name: pi4
keyboards:
  pi_09:
    path: WAITING FROM DETECTOR
    dir: ./Keyboard_1
    root: index.ahk
    hotkeys:
      {}
  pi_10:
    path: WAITING FROM DETECTOR
    dir: ./Keyboard_2
    root: index.ahk
    hotkeys:
      {}
addresses:
  detector: 0.0.0.0
  server:
    ipv4: 192.168.0.14
    port: 9090
perms:
  ssh: true
