# Config for 2Keys
# ONLY FOR USE BY THE PROGRAM
# To change the config, update it on the client and run "2Keys config-update" here
addresses:
  detector: 192.168.0.100
  server:
    ipv4: 192.168.0.50
    port: 8181
keyboards:
  logitech_g810:
    path: /dev/input/by-id/usb-04d9_1203-event-kbd
    executors:
      executor-ahk:
        root: index.ahk
    root: ./logitech_g810
    detector:
      paths:
      - /dev/input/by-id/usb-Logitech_Gaming_Keyboard_G810_166A37573236-event-if01
      - /dev/input/by-id/usb-Logitech_Gaming_Keyboard_G810_166A37573236-event-kbd
      - /dev/input/by-id/usb-Logitech_Gaming_Keyboard_G810_166A37573236-if01-event-kbd
    hotkeys:
      ^!+T: TestIfRunning
  numpad_apps:
    path: /dev/input/by-id/usb-04d9_1203-event-kbd
    executors:
      executor-ahk:
        root: index.ahk
    root: ./numpad_apps
    detector:
      paths:
      - /dev/input/by-id/usb-04d9_1203-event-kbd
    hotkeys:
      $BACKSPACE$: Slack
      $NUM_+$: Firefox
      $NUM_-$: VSCode
      $NUM_/$: TestIfRunning
      NUM0$BACKSPACE$: Slack
      NUM0$NUM_+$: FirefoxLaunch
      NUM0$NUM_-$: VSCodeLaunch
      NUM0NUM1: ExcelLaunch
      NUM0NUM2: PowerpointLaunch
      NUM0NUM5: TerminalLaunch
      NUM0NUM6: ExplorerLaunch
      NUM0NUM8: PremiereLaunch
      NUM0NUM9: DiscordLaunch
      NUM1: Excel
      NUM2: Powerpoint
      NUM3: Teams
      NUM5: Terminal
      NUM6: Explorer
      NUM7: Teams
      NUM8: Premiere
      NUM9: Discord
name: KeyboardOfMacros
perms:
  ssh: true
