name: Tests in a container

#on:
#  push:
#    branches: [ master, v1 ]
#  pull_request:
#    branches: [ master, v1 ]

on: push

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    env:
     TWOKEYS_OOBE_NET_TEST_INTERFACE: vEthernet (nat)

    steps:
    - uses: actions/checkout@v2
    - name: Install protoc
      run: choco install protoc
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - name: Setup native modules
    #   run: yarn global add windows-build-tools
    - name: Install packages
      run: yarn
    - name: Compile
      run: |
        yarn wsrun -mtc precompile
        yarn build -v
    - name: Run stuff
      run: yarn wsrun -msc test:container

