name: "@twokeys/detector-desktop: isolated tests"

on: push

jobs:
  build:
    runs-on: macos-latest
    continue-on-error: true

    strategy:
      matrix:
        node-version: [12.x]
    
    env:
     TWOKEYS_OOBE_NET_TEST_INTERFACE: vEthernet (nat)
     working-dir: detectors/detector-desktop/controller

    steps:
    - uses: actions/checkout@v2
    - name: Install protoc
      run: brew install protobuf
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - name: Setup native modules
    #   run: yarn global add windows-build-tools
    - name: Install packages
      run: |
        yarn
      working-directory: ${{ env.working-dir }}
    - name: Compile
      if: ${{ always() }}
      run: |
        yarn build -v
      working-directory: ${{ env.working-dir }}
    - name: Run tests
      if: ${{ always() }}
      run: yarn coverage:isolated
      working-directory: ${{ env.working-dir }}
    - uses: codecov/codecov-action@v1
      if: ${{ always() }}

