name: Node JS Server tests

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    env:
        CI: true
        NODE_ENV: development

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Add node-gyp
      run: |
        cd server
        yarn global add node-gyp@latest
        npm i -g node-gyp@latest
    - name: Install deps
      run: yarn
    - name: Build modules
      run: yarn run build
    - name: Run tests
      run: yarn test
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./server/coverage/lcov.info #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
