name: Node JS Server tests

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd ./server
        yarn
        yarn run build --if-present
        yarn test
      env:
        CI: true
        NODE_ENV: development
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./server/coverage/lcov.info #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
