# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  server:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [13.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd server yarn install --frozen-lockfile
      name: Install Deps (Yarn)
      working-directory: ./server
    - name: Install AHK
      run: yarn run ts-node ./scripts/bootstrap.ts
      working-directory: ./server
    - run: yarn run coverage
      name: Run tests & Coverage
      working-directory: ./server
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        file: ./server/coverage/lcov.info
