name: Node JS Server tests

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup MSBuild.exe # Needed so things work
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup VS Dev Environment # Needed so things work
      uses: seanmiddleditch/gha-setup-vsdevenv@v1
    - name: Install deps
      run: |
        cd server
        npm config set msvs_version 2019
        npm ci
      env:
        CI: true
        NODE_ENV: development
    - name: Run tests
      run: |
        cd server
        npm test
      env:
        CI: true
        NODE_ENV: development
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./server/coverage/lcov.info #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
