# Automates adding of TODOs
name: "TODO issue creator"
on: ["push"]
jobs:
  todo:
    name: TODO to Issue
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v1.2-beta"
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "// TODO:"
          COMMENT_MARKER: "//"
        id: "todo"
      - name: "TODO to Issue for Python"
        uses: "alstr/todo-to-issue-action@v1.2-beta"
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "# TODO:"
          COMMENT_MARKER: "#"
        id: "todopy"
  fixme:
    name: FIXME to Issue
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "FIXME to Issue"
        uses: "alstr/todo-to-issue-action@v1.2-beta"
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "// FIXME:"
          COMMENT_MARKER: "//"
        id: "fixme"